---
cpi: onrack
properties:
  key_name:  bats
  pool_size: 1
  instances: 1
  uuid: 350ddba1-ce7a-4909-9f1a-c44e16b6a9e1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw
    version: 3104
  networks:
  - name: default
    static_ip: 172.31.129.5
    type: manual
    cidr: 172.31.129.0/22
    reserved: [172.31.129.15]
    static: [[172.31.129.10-172.31.129.14]]
    gateway: 172.31.128.1
